accounts/urls.py
from django.urls import path 
from django.contrib.auth import views as views2
from django.urls import path
from . import views
app_name ="accounts"
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/<slug:slug>',views.profile,name='profile'),
    path('profile/edit/<slug:slug>',views.editprofile,name='profile_edit'),
    
    path("login/", views2.LoginView.as_view(), name="login"),
    path("logout/", views2.LogoutView.as_view(), name="logout"),
    path("password_change/", views2.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",views2.PasswordChangeDoneView.as_view(),name="password_change_done",),
    path("password_reset/", views2.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/",views2.PasswordResetDoneView.as_view(),name="password_reset_done",),
    path("reset/<uidb64>/<token>/",views2.PasswordResetConfirmView.as_view(),name="password_reset_confirm",),
    path("reset/done/",views2.PasswordResetCompleteView.as_view(),name="password_reset_complete",),
]

ask/urls.py
from django.urls import path 
from . import views
app_name ="ask"
urlpatterns = [
    
    path('add/',views.ask,name='add_question'),
    path('',views.question_list,name='question_list'),
    path('tag/<slug:tag_slug>',views.question_list,name='question_list_by_tag'),
    path('question/<int:id>',views.question_detail,name='question_detail'),
    path('question/<int:id>/like',views.like,name='question_like'),
    path('question/<int:qid>/likeanswer/<int:id>',views.like_answer,name='like_answer'),
    path('question/<int:id>/delete',views.delete_question,name='delete_question'),
    path('question/edit/<int:id>',views.edit_question,name='edit_question'),



]

friend/urls.py
from django.urls import path 

from .views import add_friend , accept_friend , friend_list ,un_friend , add_message_list


app_name ="friend"


urlpatterns = [
    
    path('<str:slug>/add',add_friend,name='add_friend'),
    path('<str:slug>/accept',accept_friend,name='accept_friend'),
    path('friends/list',friend_list,name='friend_list'),
    path('<str:slug>/delete',un_friend,name='un_friend'),
    path('chat/<str:slug>',add_message_list,name='chat'),
    
]

group/urls.py
from django.urls import path 

from . import views
app_name ="group"
urlpatterns = [
    
    path('addgroup/',views.add_group,name='add_group'),
    path('groups/',views.group_list,name='group_list'),
    path('group/<int:id>',views.group_detail,name='group_detail'),
    path('group/<int:id>/join',views.join_group,name='join_group'),
    path('group/<int:pid>/black_list/<int:gid>',views.block_unblock_member,name='block_unblock_member'),
    path('group/<int:id>/delete',views.delete_group,name='delete_group'),
    path('group/edit/<int:id>',views.edit_group,name='edit_group'),


]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import handel404 , handel500

from .notification_context import mark_notifications_as_read , delete_notification  , mark_notification_read

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('ask.urls',namespace='ask')),
    path('admin/', admin.site.urls),
    path('group/', include('group.urls',namespace='group')),
    path('friend/', include('friend.urls',namespace='friend')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('notification/', mark_notifications_as_read, name='notification' ),
    path('notification/<int:id>/delete', delete_notification, name='notification_button' ),
    path('notification/<int:id>/read', mark_notification_read, name='notification_read' ),


    ]

handlr404 = 'project.views.handel404'
handlr500 = 'project.views.handel500'

ask/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from group.models import Group
from taggit.managers import TaggableManager
# Create your models here.
class Question(models.Model):
    title            = models.CharField(max_length=1000  )
    content          = models.TextField(max_length=40000, blank=True  )
    rating           = models.IntegerField(null=True, blank=True)
    created_at       = models.DateTimeField(auto_now=True,auto_created=True,null=True, blank=True,)
    last_edit        = models.DateTimeField(auto_created=True,null=True, blank=True)
    user             = models.ForeignKey(User,on_delete=models.CASCADE,related_name="Question_user")
    like             = models.ManyToManyField(User , blank=True ,related_name="Question_like")
    group            = models.ForeignKey(Group ,on_delete=models.CASCADE, blank=True ,null=True,related_name="group_question")
    tags             = TaggableManager(blank=True)

    class Meta:
        ordering  = ['-created_at']
        get_latest_by =  'created_at'
        

    def get_absolute_url(self):
        return reverse("ask:question_detail", kwargs={"id": self.pk})
        
    def __str__(self) -> str:
        return self.title

class Answer(models.Model):
    # TODO: most live answer
    user       = models.ForeignKey(User, on_delete=models.CASCADE,related_name="Answer_user")
    content    = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now=True, auto_created=True)
    question   = models.ForeignKey(Question, on_delete=models.CASCADE,related_name="question") 
    like       = models.ManyToManyField(User , blank=True ,related_name="Answer_like")

    class Meta:
        get_latest_by = 'created_at'
        ordering  = ['-created_at']

    def __str__(self) -> str:
        return str(self.content)

ask/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.urls import reverse
from .form import AskForm , AnswerForm
from django.contrib.auth.decorators import login_required
from accounts.models import  Notification ,Profile
from group.models import  Group
from datetime import datetime
from django.db.models import Q
from accounts.models import Profile
from .models import Question , Answer 
from taggit.models import Tag
from django.contrib import messages


@login_required
def question_list(request,tag_slug=None):
        
    if request.method == 'POST':
        tag = None
        search_info = request.POST

        
        question_contain_word = search_info.get('search_txt', '')
        search_from_time = search_info.get('from', None)
        search_to_time = search_info.get('to', None)
        questions = Question.objects.filter(group=None)


        
        if question_contain_word:
            questions = questions.filter(
                Q(content__icontains=question_contain_word) |
                Q(title__icontains=question_contain_word) 
            )
        
        if search_from_time:
            questions = questions.filter(created_at__gte=search_from_time)
        
        if search_to_time:
            questions = questions.filter(created_at__lte=search_to_time)
        


    else:
        tag = None
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            questions = Question.objects.filter(group=None,tags__in=[tag])
        else:
            questions = Question.objects.filter(group=None)

        
    groups = Group.objects.all()
    profile   = Profile.objects.get( user = request.user )
    myfriends = profile.confirmed_friend.all()
    


    return render(request,'ask/questions.html',
        {
        "my_friends": myfriends,
        'questions':questions,
        'groups':groups,
        'tag':tag,
        })


@login_required
def question_detail(request, id):
    # TODO: count of people who click to view post

    question = get_object_or_404(Question, pk=id)
    answers = Answer.objects.filter(question=question)

    if request.method == 'POST':
        answer = Answer.objects.create(
            user=request.user,
            question=question,
            content=request.POST['content']
        )
        if question.user != request.user :

            notification = Notification.objects.create( from_user = request.user ,
                                                    to_user = question.user ,
                                                    content="question_answered")

        messages.success(request, 'Answer submitted successfully!')

        return redirect('ask:question_detail', id=question.pk)


    return render(request, 'ask/question_detail.html', {'question': question,'answers': answers})

@login_required
def ask(request):
    if request.method == 'POST':
        form = AskForm(request.POST)
        if form.is_valid() :
            myform = form.save(commit=False)
            myform.user = request.user
            myform.save()
            form.save_m2m()
            messages.success(request, 'Question submitted successfully!')

            return redirect(reverse('ask:question_list'))
        messages.success(request, 'make space between tags! or make it null')
    else:
        form = AskForm()

    return render(request,"ask/ask_question.html",{"form":form})

@login_required
def like(request, id ):
    
    question = get_object_or_404(Question, id=id)
    if request.user in question.like.all() :
        question.like.remove(request.user)
    else :
        question.like.add(request.user)
        if question.user != request.user :
            notification = Notification.objects.create( from_user = request.user ,
                                                    to_user = question.user ,
                                                    content="question_liked")
        messages.success(request, 'You liked the question!')
        


    # return redirect(reverse('ask:question_detail', args=[question.id]))
    return redirect(reverse('ask:question_list'))

@login_required
def like_answer(request, id , qid):
    # TODO: best Answer in the head of answers

    question = get_object_or_404(Question, id=qid)
    answer = get_object_or_404(Answer, id=id)
    
    if request.user in answer.like.all() :
        answer.like.remove(request.user)
    else :
        answer.like.add(request.user)
        if answer.user != request.user :
            notification = Notification.objects.create( from_user = request.user ,
                                                    to_user = answer.user ,
                                                    content="answer_liked")
        messages.success(request, 'You liked the answer!')

    return redirect(reverse('ask:question_detail', args=[question.id]))

@login_required
def delete_question(request, id):
    question = get_object_or_404(Question, id=id)
    if request.user == question.user :
        question.delete()
        messages.success(request, 'You delete question!')

        return redirect('ask:question_list')
    return redirect('ask:question_detail', id=question.id)



@login_required
def edit_question(request,id):
    question = get_object_or_404(Question,pk=id)
    if request.method == 'POST':
        if request.user == question.user:
            form = AskForm(request.POST,instance=question)
            if form.is_valid() :
                myform = form.save(commit=False)
                myform_created_at=myform.created_at
                myform.user = request.user
                myform.last_edit = datetime.now()
                myform.created_at = myform_created_at
                myform.save()
                messages.success(request, 'You edit question!')
                

                return redirect(('ask:question_detail'),id=question.id)

    else:

        form = AskForm(instance=question)


    return render(request,"ask/edit_question.html",{"form":form})

ask/templates/ask/question_detail.html
{% extends "base.html" %}
{% block body %}
<main class="profile-page layout layout--2">
    <div class="container">
      <!-- Room Start -->
      <div class="room">
        <div class="room__top">
          <div class="room__topLeft">
            <a href="{{request.META.HTTP_REFERER}}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Question Detail</h3>
          </div>

          {% if request.user == question.user %}
          <div class="room__topRight">
            <a href='{% url "ask:edit_question" question.id %}'>
              <svg
                enable-background="new 0 0 24 24"
                height="32"
                viewBox="0 0 24 24"
                width="32"
                xmlns="http://www.w3.org/2000/svg"
              >
                <title>edit</title>
                <g>
                  <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                </g>
                <g>
                  <g>
                    <path
                      d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                    />
                  </g>
                  <g>
                    <path
                      d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                    />
                  </g>
                </g>
              </svg>
            </a>
            
            <a href='{% url "ask:delete_question" question.id %}' onclick="">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>delete question</title>
                <path
                  d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
                </path>
              </svg>
            </a>
          </div>
{% endif %}

      
        </div>
        
        <div class="room__box scroll">
          <div class="room__header scroll">
            <div class="room__info">
              <h3>{{question.title}}</h3>
              <span>{{question.created_at|timesince}}</span>
            </div>
            <div class="room__hosted">
              <p>Created By</p>
              <a href="{% url 'accounts:profile' question.user %}" class="room__author">

                <div class="avatar avatar--small">
                  <img src="static/assets/avatar.svg" />
                </div>
                <span>@{{question.user}}</span>
              </a>
            </div>
            <div class="room__details">
              {{question.content}}
            </div>
            
            {% if request.user in question.like.all %}
                  
            <div class="thread__delete">
                 
              <a style="font-size: x-large;" href="{% url 'ask:question_like' id=question.id %}"> ♥</a> 
              <a style="font-size: small;" href="{% url 'ask:question_like' id=question.id %}">{{question.like.count}}</a> 
            </div>
            
            {% else %}
            
          <div class="thread__delete">
            <a  style="font-size: x-large;color:thistle " href="{% url 'ask:question_like' id=question.id %}"> ♥</a> 
            <a style="font-size: small;" href="{% url 'ask:question_like' id=question.id %}">{{question.like.count}}</a> 
          </div>
                
              {% endif %}
          </div>



            <div class="room__message">
                <form action='{% url "ask:question_detail" question.id %}' method="POST">
                  {% csrf_token %}
                  <input name="content" placeholder="Write your answer here..." />
                </form>
              </div>





          <div class="room__conversation">
            <div class="threads scroll">
                
                {% for answer in answers %}
                    
                    <br>
                <div class="container" style=" width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: var(--color-dark); color: var(--color-); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
                  <div class="thread__top">
                  <div class="thread__author">
                    {% comment %} <div class="container" style=" width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: var(--color-dark); color: var(--color-); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);"> {% endcomment %}

                    <a href="{% url 'accounts:profile' answer.user %}" class="thread__authorInfo">
                      <div class="avatar avatar--small">
                        <img src="static/assets/avatar.svg" />
                      </div>
                      <span>@{{answer.user}}</span>
                    </a>
                    <span class="thread__date">{{answer.created_at|timesince}}</span>
                  </div>
                  
                  
                  {% if request.user in answer.like.all %}
                  
                <div class="thread__delete">
                     
                  <a style="font-size: x-large;" href="{% url 'ask:like_answer' qid=question.id id=answer.id %}"> ♥</a> 
                  <a style="font-size: small;" href="{% url 'ask:like_answer' qid=question.id id=answer.id %}">{{answer.like.count}}</a> 
                </div>
                
                {% else %}
                
              <div class="thread__delete">
                <a  style="font-size: x-large;color:thistle " href="{% url 'ask:like_answer' qid=question.id id=answer.id %}"> ♥</a> 
                <a style="font-size: small;" href="{% url 'ask:like_answer' qid=question.id id=answer.id %}">{{answer.like.count}}</a> 
              </div>
                    
                  {% endif %}
                  
                  
                </div>
                <div style="color:var(--color-gray);" class="thread__details">
                  <br>
                  {{answer.content}}
                </div>
              </div>
              {% endfor %}



            </div>
          </div>
        </div>
      </div>
      <!-- Room End -->

      <!--   Start -->
      <div class="participants">
        <h3 class="participants__top">Participants <span>({{question.like.count}} Likes)/({{answers.count}} answers)</span></h3>
        <div class="participants__list scroll">
          
          {% for member in question.like.all %}
            
          
          <a href="{% url 'accounts:profile' member %}" class="participant">
            <div class="avatar avatar--medium">
              <img src="static/assets/avatar.svg" />
            </div>
            <p>
              {{member.first_name}} {{member.last_name}} 
              <span>@{{member}}</span><span>♥</span>  
            </p>
          </a>
          {% endfor %}
        </div>
      </div>
      <!--  End -->
    </div>
  </main>
{% endblock body %}


  


      <!--   Start -->
      <!--  End -->

ask/templates/ask/questions.html
{% extends "base.html" %}
{% block body %}

<main class="layout layout--3">
<div class="container" style=" width: 100%;  border: 2px solid rgb(94, 94, 94);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">



    <!-- Groups Start -->
    <div class="container" style=" width: 100%;  border: 2px solid rgb(94, 94, 94);  border-radius: 40px; padding: 20px; background-color: var(--color-dark);:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
            <div class="container1  " style="width: 100%; border: 2px solid rgb(94, 94, 94); border-radius: 40px; padding: 20px; background-color: var(--color-dark-medium); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
            <a style="padding: 10px 20px; background-color: #ff6b6b; color: var(--color-dark); border-radius: 10px; text-decoration: none; margin-bottom: 20px;" href='{% url "group:group_list" %}' class="roomListRoom__author" style="text-decoration: none; color: var(--color-dark-light);">
              <h2>Quistify Groups </h2></a>
            <div class="activities" style="text-align: center; margin-bottom: 20px;">
              <button id="toggleGroupsBtn" class="toggle-button" style="display: block; margin: 0 auto 20px; padding: 10px; background-color: transparent; border: none; cursor: pointer; font-size: 18px; color: #ff6b6b;">
                <span id="arrow " class="arrow2">New Groups</span>
              </button>
              <a class="btn btn--pill" href='{% url "group:add_group" %}'>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>Create Question</title>
                  <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                  ></path>
                </svg>
              </a>
            </div>
           
          </div>

    
      <div id="groupsContainer" style="display: none; margin-top: 20px;">

        {% for group in groups|slice:":5" %}

        <!-- صندوق لكل مجموعة -->
        <div class="container" style="width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 20px; padding: 15px; margin-bottom: 20px; background: var(--color-dark-medium); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
          
          <!-- القائد والمعلومات الأساسية -->
          <div class="activities__boxHeader" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
            <a href='{% url "group:group_detail" group.id %}' class="roomListRoom__author" style="font-weight: bold; text-decoration: none; color: #ff6b6b;">
              @{{group.leader}}
            </a>
          </div>
    
          <!-- المحتوى الأساسي -->
          <div class="activities__boxContent" style="padding: 10px; border: 1px solid rgb(222, 101, 101); border-radius: 10px; background: rgba(137, 142, 137, 0.351); color: var(--color-dark-light);">
            <p style="margin: 0; font-size: 16px; color: #ff6b6b;">
              “<a href='{% url "group:group_detail" group.id %}' style="text-decoration: none; color: #ff6b6b;">{{group.name}}</a>”
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    
    
    
    <!-- Groups End -->


    <!-- Question List Start -->
    <div class="roomList">
      <div class="container" style=" width: 100%;  border: 2px solid rgb(94, 94, 94);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
        <div class="roomList__header">

          {% if tag %}

          <h2>Questions in tag: {{tag}}</h2>
          {% else %}

          <h2>Questions</h2>
          {% endif %}

        <p style="color:var(--color-gray); " >{{questions.count}} Questions available</p>
        <a class="btn btn--pill" href='{% url "ask:add_question" %}'>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>Create Question</title>
            <path
            d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
        </a>
      
      </div>
      
      {% for question in questions %}
      <div class="roomListRoom">
        <div class="roomListRoom__header">
          <a href='{% url "accounts:profile" question.user %}' class="roomListRoom__author">
            <div class="avatar avatar--small">
              <img src={{question.user.image}} />
            </div>
            <span>@{{question.user}}</span>
          </a>
          <div class="roomListRoom__actions">
            <span>{{question.created_at|timesince}}</span>
          </div>
        </div>
        <div class="roomListRoom__content">
          <a target="_blank" href='{% url "ask:question_detail" question.id %}'>{{question.title}}</a>
          <p style="color:var(--color-gray); " >
            {{question.content}}
          </p>
        </div>
        {% if request.user in question.like.all %}

        <div class="roomListRoom__meta">
          <a  style="font-size: x-large;color:red " class="roomListRoom__joined" href="{% url 'ask:question_like' id=question.id %}"> ♥</a> 
          <a style="font-size: x-small; margin-right:auto;" class="roomListRoom__joined" href="{% url 'ask:question_like' id=question.id %}">{{question.like.count}} Likes</a> 
          {% for tag in question.tags.all %}
          <a href="{% url 'ask:question_list_by_tag' tag.slug %}">
            <p class="roomListRoom__topic">{{tag.name}}</p>
          </a>
          {% endfor %}
         </div>
        </div>
        {% else %}
        <div class="roomListRoom__meta">
          <a  style="font-size: x-large;color:thistle " class="roomListRoom__joined"  href="{% url 'ask:question_like' id=question.id %} " > ♥</a> 
          <a style="font-size: x-small; margin-right:auto;" class="roomListRoom__joined" href="{% url 'ask:question_like' id=question.id %}">{{question.like.count}} Likes</a> 
          {% for tag in question.tags.all %}
          <a href="{% url 'ask:question_list_by_tag' tag.slug %}">
            <p class="roomListRoom__topic">{{tag.name}}</p>
          </a>
          {% endfor %}
          </div>
        </div>
        {% endif %}

      {% endfor %}
      
    </div>
    </div>
    <!-- Question List End -->

<!-- Friends Start -->
<div class="container1" style=" width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: var(--color-dark-medium); color: var(--color-main); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
  
  <div class="activities-content">
    <div class="toggle-button" id="toggleButton"><span class="arrow">▼</span><h2 >My Friends</h2></div>
  </div>
  <div class="activities-content" id="activitiesContent" style="display: none;">
    <hr>
    {% for friend in my_friends %}
    <div class="activities__boxHeader roomListRoom__header" style="margin-top: 10px; border: 2px solid var(--color-dark); border-radius: 40px; padding: 20px; background: var(--color-dark-light); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
    <div class="activities__boxHeader roomListRoom__header" style="margin-top: 10px; border: 2px solid var(--color-dark); border-radius: 40px; padding: 20px; background: var(--color-dark-light); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
        <a href='{% url "accounts:profile" friend %}' class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="static/assets/avatar.svg" />
          </div>
          <p>{{friend.username}}<span>{{friend.first_name}} {{friend.last_name}}</span></p>
        </div>
        <div class="activities__boxHeader roomListRoom__header" style="margin-top: 10px; border: 2px solid var(--color-dark); border-radius: 40px; padding: 20px; background: var(--color-dark-light); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">

        <a href="{% url 'friend:chat' friend %}">֍</a>
      </a>
    </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
<!-- Friends End -->



</div>
</main>

<script>
  const toggleButton = document.getElementById('toggleButton');
  const activitiesContent = document.getElementById('activitiesContent');
  const arrow = document.querySelector('.arrow');
  
  const toggleBtn = document.getElementById('toggleGroupsBtn');
  const groupsContainer = document.getElementById('groupsContainer');
  const arrow2 = document.getElementById('arrow2');
  
  // تهيئة حالة العرض الافتراضية
  activitiesContent.style.display = 'none'; // تأكد من أن محتوى الأنشطة مخفي افتراضيًا
  groupsContainer.style.display = 'none'; // تأكد من أن حاوية المجموعات مخفية افتراضيًا
  
  toggleButton.addEventListener('click', () => {
    // تغيير حالة العرض لمحتوى الأنشطة
    if (activitiesContent.style.display === 'none') {
      activitiesContent.style.display = 'block';
      arrow.classList.add('rotate'); // إضافة الكلاس للدوران
    } else {
      activitiesContent.style.display = 'none';
      arrow.classList.remove('rotate'); // إزالة الكلاس للدوران
    }
  });
  
  toggleBtn.addEventListener('click', () => {
    // تغيير حالة العرض لحاوية المجموعات
    if (groupsContainer.style.display === 'none') {
      groupsContainer.style.display = 'block';
      arrow2.classList.add('rotate'); // إضافة الكلاس للدوران

    } else {
      groupsContainer.style.display = 'none';
      arrow2.classList.remove('rotate'); // إزالة الكلاس للدوران

    }
  });
  
</script>

{% comment %} var(--color-dark-medium) {% endcomment %}

{% endblock body %}