accounts/urls.py
from django.urls import path 
from django.contrib.auth import views as views2
from django.urls import path
from . import views
app_name ="accounts"
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/<slug:slug>',views.profile,name='profile'),
    path('profile/edit/<slug:slug>',views.editprofile,name='profile_edit'),
    
    path("login/", views2.LoginView.as_view(), name="login"),
    path("logout/", views2.LogoutView.as_view(), name="logout"),
    path("password_change/", views2.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",views2.PasswordChangeDoneView.as_view(),name="password_change_done",),
    path("password_reset/", views2.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/",views2.PasswordResetDoneView.as_view(),name="password_reset_done",),
    path("reset/<uidb64>/<token>/",views2.PasswordResetConfirmView.as_view(),name="password_reset_confirm",),
    path("reset/done/",views2.PasswordResetCompleteView.as_view(),name="password_reset_complete",),
]

ask/urls.py
from django.urls import path 
from . import views
app_name ="ask"
urlpatterns = [
    
    path('add/',views.ask,name='add_question'),
    path('',views.question_list,name='question_list'),
    path('tag/<slug:tag_slug>',views.question_list,name='question_list_by_tag'),
    path('question/<int:id>',views.question_detail,name='question_detail'),
    path('question/<int:id>/like',views.like,name='question_like'),
    path('question/<int:qid>/likeanswer/<int:id>',views.like_answer,name='like_answer'),
    path('question/<int:id>/delete',views.delete_question,name='delete_question'),
    path('question/edit/<int:id>',views.edit_question,name='edit_question'),



]

friend/urls.py
from django.urls import path 

from .views import add_friend , accept_friend , friend_list ,un_friend , add_message_list


app_name ="friend"


urlpatterns = [
    
    path('<str:slug>/add',add_friend,name='add_friend'),
    path('<str:slug>/accept',accept_friend,name='accept_friend'),
    path('friends/list',friend_list,name='friend_list'),
    path('<str:slug>/delete',un_friend,name='un_friend'),
    path('chat/<str:slug>',add_message_list,name='chat'),
    
]

group/urls.py
from django.urls import path 

from . import views
app_name ="group"
urlpatterns = [
    
    path('addgroup/',views.add_group,name='add_group'),
    path('groups/',views.group_list,name='group_list'),
    path('group/<int:id>',views.group_detail,name='group_detail'),
    path('group/<int:id>/join',views.join_group,name='join_group'),
    path('group/<int:pid>/black_list/<int:gid>',views.block_unblock_member,name='block_unblock_member'),
    path('group/<int:id>/delete',views.delete_group,name='delete_group'),
    path('group/edit/<int:id>',views.edit_group,name='edit_group'),


]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import handel404 , handel500

from .notification_context import mark_notifications_as_read , delete_notification  , mark_notification_read

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('ask.urls',namespace='ask')),
    path('admin/', admin.site.urls),
    path('group/', include('group.urls',namespace='group')),
    path('friend/', include('friend.urls',namespace='friend')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('notification/', mark_notifications_as_read, name='notification' ),
    path('notification/<int:id>/delete', delete_notification, name='notification_button' ),
    path('notification/<int:id>/read', mark_notification_read, name='notification_read' ),


    ]

handlr404 = 'project.views.handel404'
handlr500 = 'project.views.handel500'

group/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Group(models.Model):
    leader          = models.ForeignKey(User,on_delete=models.CASCADE,related_name="Leader",unique=False)
    name            = models.CharField(max_length=50,unique=True)
    bio             = models.TextField(max_length=50,null=True,blank=True)
    created_at      = models.DateTimeField(auto_now=True,auto_created=True,null=True, blank=True)
    members         = models.ManyToManyField(User,blank=True ,related_name="Members",unique=False)
    black_list      = models.ManyToManyField(User,blank=True ,related_name="blacklist",unique=False)
    
    class Meta:
        get_latest_by =  'created_at'

    def get_absolute_url(self):
        return reverse("group", kwargs={"id": self.pk})
    
    def save(self,*args, **kwargs):
        if not self.leader :
            self.leader = self.user
        super(Group,self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name

group/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from .models import Group 
from ask.models import Question
from accounts.models import  Notification ,Profile
from datetime import datetime
from django.urls import reverse
from .form import AddGroupForm
from ask.form import AskForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages


@login_required
def add_group(request):
    if request.method == 'POST':
        form = AddGroupForm(request.POST)

        if form.is_valid() :
        
            myform = form.save(commit=False)
            myform.leader = request.user
            myform.save()
            myform.members.add( request.user)
            messages.success(request, 'group successfully publishe!')

            return redirect(reverse('group:group_list'))
    else:
        form = AddGroupForm()

    return render(request,"group/add_group.html",{"form":form})

@login_required
def group_list(request):
    groups = Group.objects.all().order_by('created_at')

    mygroups=[]
    for group in groups : 
        if request.user in group.members.all() :
            mygroups.append(group)
    
    not_my_groups=[]
    for group in groups : 
        if request.user not in group.members.all() :
            not_my_groups.append(group)


    return render(request,'group/groups.html',{'mygroups':mygroups,'groups':groups,'user':request.user})

@login_required
def join_group(request,id):
    group = get_object_or_404(Group, id=id)
    
    if request.user in group.members.all() :
        group.members.remove(request.user)
    
    elif request.user  not in group.black_list.all() :
        group.members.add(request.user)
        if group.leader != request.user :
            notification = Notification.objects.create( from_user = request.user ,
                                            to_user = group.leader ,
                                            content="group_joined")
            
        messages.success(request, 'You had joined the group!')

    return redirect(reverse('group:group_list'))

@login_required
def group_detail(request,id):
    group = get_object_or_404(Group, id=id)
    
    if request.method == 'POST': 

        if "title" in (request.POST.keys()) :
            form = AskForm(request.POST)
            if form.is_valid():
                myform = form.save(commit=False)
                myform.user = request.user
                myform.group = group
                myform.save()
                return redirect('group:group_detail', id=group.id)
            else:
                form = AskForm()

        else :
            form = AskForm()
            search_info = request.POST
            question_contain_word = search_info['search_txt']
            search_from_time = search_info['from']
            search_to_time = search_info['to']
            questions = Question.objects.filter(group=group)
            if question_contain_word:
                questions = questions.filter(
                    Q(content__icontains=question_contain_word) |
                    Q(title__icontains=question_contain_word) 
            )
        
        if search_from_time:
            questions = questions.filter(created_at__gte=search_from_time)
        
        if search_to_time:
            questions = questions.filter(created_at__lte=search_to_time)
        

        #fulter end        
            
        if request.user in group.members.all():

                return render(request, 'group/group_detail.html', {'group': group,'questions': question,'form': form})

        else:
                messages.info(request, 'join to group to see questions!')

                return redirect(reverse('group:group_list'))

    else :
        form = AskForm()
        question = Question.objects.filter(group=group)

        if request.user in group.members.all():

            return render(request, 'group/group_detail.html', {'group': group,'questions': question,'form': form})

        else:
                messages.info(request, 'You don,t in this group to see questions!')

                return redirect(reverse('group:group_list'))
    

@login_required
def delete_group(request, id):
    group = get_object_or_404(Group, id=id)
    if request.user == group.leader :
        group.delete()
        messages.info(request, 'You have delete the group!')
        return redirect('group:group_list')
    else:
        group.members.remove(request.user)

        messages.info(request, 'You have leave the group!')
        return redirect('group:group_list')

    return redirect('group:group_detail', id=group.id)


@login_required
def edit_group(request,id):
    group = get_object_or_404(Group,pk=id)
    if request.method == 'POST':

        if request.user == group.leader:
            form = AddGroupForm(request.POST,instance=group)
            if form.is_valid() :
                created_time = group.created_at 
                myform = form.save(commit=False)
                myform.leader = request.user
                myform.last_edit = datetime.now()
                myform.created_at = created_time
                myform.save()
                messages.success(request, 'You have edit the group!')
                

                return redirect(('group:group_detail'),id=group.id)

    else:

        form = AddGroupForm(instance=group)


    return render(request,"group/edit_group.html",{"form":form})


def block_unblock_member(request,slug,id):
    group = get_object_or_404(Group,pk=id)
    profile = Profile.objects.filter( slug = slug )
    
    if request.user == group.leader :
        group.black_list.add(profile.user)
        group.members.remove(profile.user)
        return redirect('group:block_unblock_member', id=group.id)
        
    elif request.user == group.leader :
        group.black_list.remove(profile.user)
        group.members.add(profile.user)
        
        return redirect('group:block_unblock_member', id=group.id)
        
    return render(request,"group/black_list.html",{"group":group})

group/templates/group/add_group.html
{% extends 'base.html' %}

{% block body %}

<main class="create-room layout">
  <div class="container">
    <div class="container" style=" width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: var(--color-dark); color: var(--color-); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Make a Group</h3>
        </div>
      </div>
      <div class="layout__body">
        
        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group">
            <label for="room_name">Title : </label>
            {{form.name}}
          </div>
          <div class="form__group">
            <label for="room_description">Bio :</label>
            {{form.bio}}
          </div>



          <div class="form__action">
            <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
            <button class="btn btn--main" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock body %}

group/templates/group/black_list.html
{% extends "base.html" %}
{% block body %}

<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Your Friends</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input placeholder="Search for Friends" />
          </label>
        </form>

        <ul class="topics__list">
          
          {% for friend in friend_list %}
          <li>
            <a href="{% url 'friend:un_friend' slug=friend %}" class="active">@{{friend.username}}  </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock body %}

group/templates/group/edit_group.html
{# Assumes you set up the password_reset view in your URLconf #}
{% extends "base.html" %}

{% block body %}

<main class="create-room layout">
    <div class="container" style=" width: 100%;  border: 2px solid var(--color-main);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-main); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
    <div class="container" style=" width: 100%;  border: 2px solid var(--color-main);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-main); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
      <div class="layout__boxHeader" style=" width: 100%;  border: 2px solid var(--color-main);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-main); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">

        <div class="layout__boxTitle" >
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Edit Group</h3>
        </div>
      </div>
      <div class="layout__body">
        
<form class="form" action="" method="POST">
  {% csrf_token %}
  <div class="form__group">
    
  <label for="room_name">Group Title</label>
  {{form.name}}
  <label for="room_description">Group Bio</label>
  {{form.bio}}
  {% comment %} <input type="submit" value="Edit" class='btn-edit-profile' > {% endcomment %}
</form>

<div class="form__action">
  <a class="btn btn--dark" href="{{request.META.HTTP_REFERER}}">Cancel</a>
  <button class="btn btn--main" type="submit">Edit</button>
</div>
</form>
</div>
</div>
</div>
</main>
  {% endblock body %}
  
  

group/templates/group/group_detail.html
{% extends "base.html" %}

{% block body %}
{% load static %}
  <main class="profile-page layout layout--3">
    <div class="container" style=" width: 100%;  border: 2px solid rgb(222, 101, 101);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
      <!-- Topics Start -->
      <div class="activities">
      
        <div class="activities__header">
          <a style="width: 100%;" href="{% url 'friend:friend_list' %}">
            <h2>Group Members</h2>
          </a>
        </div>
  
        {% for friend in group.members.all  %}
        <div class="activities__box">
          
          <div class="activities__boxHeader roomListRoom__header">
  
  
  
            <a href='{% url "accounts:profile" friend %}' class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="static/assets/avatar.svg" />
              </div>
              <p>
                {{friend.username}}
                <span>{{friend.first_name}} {{friend.last_name}}</span>
              </p>
            </a>
            
          </div>
          
        </div>
        {% endfor %}
        
        
        
      </div>
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="container" style=" width: 100%;  border: 2px solid rgb(222, 101, 101);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
        <div class="profile">

          <div class="container" style="  text-align: center; width: 100%;  border: 2px solid rgb(222, 101, 101);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
            <h1 style="font-size: x-large;   text-align: center;  ">{{group.name}}</h1>
            <a style="font-size: small; text-align: center;" href="{% url 'accounts:profile' group.leader.username %}">@{{group.leader}}</a>
            <br>
            <br>
            {% if request.user == group.leader %}
            <a href='{% url "group:edit_group" group.id %}' class="btn btn--main btn--pill">Edit Group</a>
            
            {% endif %} 
            <br>

            <h3>About</h3>
            <p>
              {% if group.bio %}
              Bio : {{group.bio}}
              <br>
              {% endif %}
              {% if group.created_at %}
              Created Since:  {{group.created_at|timesince}}
              <br>
              {% endif %}
              
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Last Questions In Group . </a>
            </h2>
          </div>
        </div>
        
        {% for question in questions  %}
          
          
        <div class="roomListRoom">
          <div class="roomListRoom__header">
            <a href='{% url "ask:question_detail" question.id %}' class="roomListRoom__author">
              <div class="avatar avatar--small active">
                {% if profile.image %}
                <img src="{{question.user.image.url}}" />
                  {% else %}
                  <img src="{% static 'assets/avatar.svg' %}" alt="User Avatar" />
                  {% endif %}
                              </div>
              <span>@{{question.user.username}}</span>
            </a>
            <div class="roomListRoom__actions">
              <span>{{question.created_at|timesince}}</span>

            </div>
          </div>
          <div class="roomListRoom__content">
            <a href='{% url "ask:question_detail" question.id %}'>{{question.title}}</a>
            <p style="color:var(--color-gray);">
            {{question.content}}
            </p>
          </div>
          <div class="roomListRoom__meta">

            
            {% if request.user in question.like.all %}
                  
            <div class="thread__delete">
                 
              <a style="font-size: x-large;" href="{% url 'ask:question_like' id=question.id %}"> ♥</a> 
              <a style="font-size: small;" href="{% url 'ask:question_like' id=question.id %}">{{question.like.count}}</a> 
            </div>
            
            {% else %}
            
          <div class="thread__delete">
            <a  style="font-size: x-large;color:thistle " href="{% url 'ask:question_like' id=question.id %}"> ♥</a> 
            <a style="font-size: small;" href="{% url 'ask:question_like' id=question.id %}">{{question.like.count}}</a> 
          </div>
                
              {% endif %}
          

          </div>
        </div>
        {% endfor %}

      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      <div class="activities">
          
        <div style="background:var(--color-dark-medium)" class="activities__box">
          
          
          
          {% if request.user == group.leader %}

          <div  class="activities__boxHeader roomListRoom__header">

              <a href='{% url "group:delete_group" group.id %}'>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>delete</title>
                  <path
                    d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
                  </path>
                </svg>
              </a>  
<br>
              <a href='{% url "group:edit_group" group.id %}'>
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>   

            </div>

            {% else %}
            
            <a href='{% url "group:delete_group" group.id %}'>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>leave group</title>
                <path
                  d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
                </path>
              </svg>
            </a>  
            {% endif %}

        <div  class="layout__body">
          <h1 style=" width: 100%;  border: 2px solid var(--color-main);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-main); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
            Ask in Group :</h1>
          <br>
          <form  class="form" action="" method="POST">
            {% csrf_token %}
            <div class="form__group" >
              <label for="room_name">Title</label>
              {{form.title}}
            </div>
            <div class="form__group">
              <label for="room_description">Details :</label>
              {{form.content}}
            </div>
  
            <div class="form__action">
              <button class="btn btn--main" type="submit">Submit</button>
            </div>
          </form>
        </div>        

       
      </div>
      <!-- Activities End -->
    </div>
  </main>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const messages = document.querySelectorAll('.messages li');
    messages.forEach(message => {
        setTimeout(() => {
            message.style.opacity = '0'; 
            setTimeout(() => {
                message.remove(); 
            }, 200); 
        }, 2000); 
    });
});
</script>
  {% endblock body %}

group/templates/group/groups.html
{% extends "base.html" %}
 

{% block body %}
<main class="create-room layout">
    <div class="container">
      <div class="container" style=" width: 100%;  border: 2px solid rgb(222, 101, 101);  border-radius: 40px; padding: 20px; background:rgba(137, 142, 137, 0.351);; color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{{request.META.HTTP_REFERER}}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>All Groups</h3>
          </div>
        </div>

        <div class="topics-page layout__body">
          <form class="header__search">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input placeholder="Search for Groups" />
            </label>
          </form>

          <ul class="topics__list">
              
              {% for group in groups  %}
              
              {% if user in group.members.all  %}
              <li>
                  <a style="text-decoration: none;" href='{% url "group:group_detail" group.id %}' class="deactive">{{group.name}} :{{group.bio|truncatechars:10}} <span style="background-color: rgba(165, 42, 42, 0.195);">{{group.members.count}}</span></a>
              </li>
              {% else %}
              
              <li>
                  <a style="text-decoration: none;" href='{% url "group:join_group" group.id %}' class="active">{{group.name}} :{{group.bio|truncatechars:10}} <span style="background-color: rgba(165, 42, 42, 0.195);">Join to :{{group.members.count}}</span></a>
              </li>

                {% endif %}
                    
            {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </main>


{% endblock body %}