accounts/urls.py
from django.urls import path 
from django.contrib.auth import views as views2
from django.urls import path
from . import views
app_name ="accounts"
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/<slug:slug>',views.profile,name='profile'),
    path('profile/edit/<slug:slug>',views.editprofile,name='profile_edit'),
    
    path("login/", views2.LoginView.as_view(), name="login"),
    path("logout/", views2.LogoutView.as_view(), name="logout"),
    path("password_change/", views2.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",views2.PasswordChangeDoneView.as_view(),name="password_change_done",),
    path("password_reset/", views2.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/",views2.PasswordResetDoneView.as_view(),name="password_reset_done",),
    path("reset/<uidb64>/<token>/",views2.PasswordResetConfirmView.as_view(),name="password_reset_confirm",),
    path("reset/done/",views2.PasswordResetCompleteView.as_view(),name="password_reset_complete",),
]

ask/urls.py
from django.urls import path 
from . import views
app_name ="ask"
urlpatterns = [
    
    path('add/',views.ask,name='add_question'),
    path('',views.question_list,name='question_list'),
    path('tag/<slug:tag_slug>',views.question_list,name='question_list_by_tag'),
    path('question/<int:id>',views.question_detail,name='question_detail'),
    path('question/<int:id>/like',views.like,name='question_like'),
    path('question/<int:qid>/likeanswer/<int:id>',views.like_answer,name='like_answer'),
    path('question/<int:id>/delete',views.delete_question,name='delete_question'),
    path('question/edit/<int:id>',views.edit_question,name='edit_question'),



]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import handel404 , handel500

from .notification_context import mark_notifications_as_read , delete_notification  , mark_notification_read

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('', include('ask.urls',namespace='ask')),
    path('admin/', admin.site.urls),
    path('group/', include('group.urls',namespace='group')),
    path('friend/', include('friend.urls',namespace='friend')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('notification/', mark_notifications_as_read, name='notification' ),
    path('notification/<int:id>/delete', delete_notification, name='notification_button' ),
    path('notification/<int:id>/read', mark_notification_read, name='notification_read' ),


    ]

handlr404 = 'project.views.handel404'
handlr500 = 'project.views.handel500'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    /* يمكن إضافة CSS مخصص هنا */
  </style>
  <link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon" />
  <link rel="stylesheet" href="{% static 'styles/style.css' %}" />  
  <title>Questify - Find Answers to your Questions!</title>
</head>

<body>
  <header class="header header--loggedIn">
    <div class="container" style="width: 70%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: rgba(137, 142, 137, 0.35); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
      <a href="/" class="header__logo">
        <img src="{% static 'assets/logo.svg' %}" alt="Questify Logo" />
        <h1>Questify</h1>
      </a>

      {% if request.user.is_authenticated %}
      <div class="container1" style="width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: rgba(137, 142, 137, 0.35); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease; text-align: center;">
        <button id="toggleButton3" style="background: rgba(222, 101, 101, 0.1); border: 2px solid rgb(222, 101, 101); cursor: pointer; font-size: 1.2em; padding: 10px 20px; border-radius: 10px; display: inline-flex; align-items: center; transition: background-color 0.3s ease, box-shadow 0.3s ease;">
          <span style="flex-grow: 1; color: var(--color-main); font-weight: bold;">Search By Data or Title or Description</span>
          <i id="toggleIcon" style="font-size: 1em; transition: transform 0.3s ease;">&#9660;</i> <!-- سهم متغير -->
        </button>
    
        <div id="toggleDiv" class="container1" style="display: none; width: 100%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: rgba(137, 142, 137, 0.35); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease;">
          <br>
  
          <form class="header__search" action="{% url 'ask:question_list' %}" method="POST" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="search-container">
              <input type="text" id="search" name="search_txt" placeholder="Search for questions... in title or description" class="search-input" style="width: 100%; padding: 10px; margin: 10px 0; border-radius: 10px; border: 1px solid rgb(222, 101, 101); transition: box-shadow 0.3s ease, background-color 0.3s ease;">
              <div class="date-range" style="margin-top: 20px;">
                <label for="from" style="color: var(--color-main); margin-right: 10px;">From</label>
                <input type="date" name="from" id="from" class="date-input" style="width: 100%; padding: 5px; margin: 10px 0; border-radius: 5px; border: 1px solid rgb(222, 101, 101);">
              </div>
              <hr style="border: none; border-top: 1px solid rgba(222, 101, 101, 0.3); margin: 20px 0;">
              <div class="date-range" style="margin-top: 20px;">
                <label for="to" style="color: var(--color-main); margin-right: 10px;">To</label>
                <input type="date" name="to" id="to" class="date-input" style="width: 100%; padding: 5px; margin: 10px 0; border-radius: 5px; border: 1px solid rgb(222, 101, 101);">
              </div>
            </div>
          </form>
        
        </div>
      </div>
      {% endif %}    

      <nav class="header__menu">
        {% if request.user.is_authenticated %}
        <div class="header__user">
          <a href="{% url 'accounts:profile' request.user.username %}">
            <div class="avatar avatar--medium active">
              <img src="{% static 'assets/avatar.svg' %}" alt="User Avatar" />
            </div>
            <p>{{ request.user.first_name }} <span>@{{ request.user.username }}</span></p>
          </a>

          <div class="notification-container">
            <a href="/notification/">🔔
              {% if notification_count > 0 %}
              <span style="color: ff6b6b;">{{ notification_count }}</span>
              {% else %}
              <span style="color: ff6b6b;">0</span>
              {% endif %}
            </a>
          </div>
        </div>
        <div class="container" style="width: 40%; border: 2px solid rgb(222, 101, 101); border-radius: 5px;  ; margin:10%;background: rgba(137, 142, 137, 0.35); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">

        <a href="{% url 'accounts:logout' %}">
          <p>Logout</p>
        </a>
      </div>

        {% else %}
        <!-- Not Logged In -->
        <a href="{% url 'accounts:login' %}">
          <img src="{% static 'assets/avatar.svg' %}" alt="Default Avatar" />
          <p>Account</p>
        </a>
        {% endif %}
      </nav>
    </div>
  </header>


</body>
<div class="container" style="width: 80%; border: 2px solid rgb(222, 101, 101); border-radius: 40px; padding: 20px; background: rgba(137, 142, 137, 0.35); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
  {% if messages %}

  <ul class="messages" style="    position: fixed; bottom: 20px;  right: 20px;  list-style: none; padding: 0; margin: 0; z-index: 1000; ">
      {% for message in messages %}
      <li class="alert alert-{{ message.tags }}" style="width: 300px; border: 2px solid rgb(94, 94, 94); border-radius: 40px; padding: 20px; background: var(--color-dark-light); color: var(--color-dark-light); box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); margin-bottom: 10px;  opacity: 1; transition: opacity 0.5s ease-out; ">
          <span style="color:var(--color-main);" >{{ message }}</span>
          <button class="close-btn" onclick="this.parentElement.style.display='none';">&times;</button>
      </li>
      {% endfor %}
  </ul>
{% endif %}
{% block body %}


{% endblock body %}
</div>
  <script>
    function validateForm() {
      var search = document.getElementById('search').value;
      if (search === "") {
        alert("Please enter a search term.");
        return false;
      }
      return true;
    }

    function closeMessage(element) {
      element.parentElement.style.display = 'none';
    }

    document.querySelectorAll('.container1').forEach(function(container) {
      container.addEventListener('mouseover', function() {
        this.style.transform = 'scale(1.02)';
        this.style.boxShadow = '0px 8px 16px rgba(0, 0, 0, 0.2)';
      });
      container.addEventListener('mouseout', function() {
        this.style.transform = 'scale(1)';
        this.style.boxShadow = '0px 4px 8px rgba(0, 0, 0, 0.1)';
      });
    });

    document.getElementById("toggleButton3").addEventListener("click", function() {
      var div = document.getElementById("toggleDiv");
      var icon = document.getElementById("toggleIcon");
      if (div.style.display === "none") {
        div.style.display = "block";
        icon.innerHTML = "&#9650;";
      } else {
        div.style.display = "none";
        icon.innerHTML = "&#9660;";
      }
    });
    document.addEventListener('DOMContentLoaded', function() {
      const messages = document.querySelectorAll('.messages li');
      messages.forEach(message => {
          setTimeout(() => {
              message.style.opacity = '0'; 
              setTimeout(() => {
                  message.remove(); 
              }, 200); 
          }, 2000); 
      });
  });
  </script>
</html>